def credit():
    print('>>Created by<<')
    print('>Abhinav Omer<') 
    print('>Nikhil Gupta<')
    print('>Bhanu Pratap Singh<')
    print("© GOLA HMS | ALL RIGHTS RESERVED")
    print('____________________________________________________________')
def terms():
	print('-----------------Terms and Conditions---------------')
	print( '1. Gola hotel management systems owns and manages the Gola hotel website')
	print()
	print('2.You warrant that you are at least 18 years of age,possess the legal authority to enter into legal agreement .You accept these conditions and use the site in accordance with such conditions.')
	print()
	print('3.According to government regulations a valid photo id has to be carrried by every person above the age of 18 years.')
	print()
	print('4.Kindly note all taxes mentioned in our package and final negotiated rates have been as per current govt. regulations.Any changes in tax structure due to govt. policies or change.in rules are applicable at the time of billing. ')
	print()
	print("© GOLA HMS | ALL RIGHTS RESERVED")
	print('___________________________________________________________')
def headoffice():
	print('>>ADDRESS AND CONTACTS<<')
	print('HEAD OFFICE:27/3 Gomti Nagar,Lucknow')
	print('CONTACT US AT: -789*******')
	print('EMAIL AT:gola_hms@gmail.com')
	print("© GOLA HMS | ALL RIGHTS RESERVED")
	print('___________________________________________________________')
